language: node_js
node_js:
- "0.12"

sudo: false

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli#develop
- cd /tmp
- /home/travis/build/appdevdesigns/opstool-hrisUserProfile/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/opstool-hrisUserProfile .
- cd opstool-hrisUserProfile
- npm install

script:
- npm test
 
